### PR TITLE
switch .r() to __call__

### PR DESCRIPTION
**Pull request by nfultz**
You mentioned in the readme that the `.r()` notation kinda sucked, how about just using `()` ? You can do that by overriding `__call__` as in this PR. 

Then you can do:

`j.foo.bar.baz[1]()
`.

### CODE REVIEW

**Comment by toejough** [comment]
I was about to open the same PR.

**Comment by skorokithakis** [comment]
Sorry, Github wasn't notifying me about PRs, so I didn't see any of these. I didn't like `__call__` because it made things implicit and looked too much like magic:

```
myobj.foo.bar.baz()
```

It makes it look as if baz is a callable, when it might be not, and it makes it hard for others to maintain your code. I'm open to a discussion about it, though!

**Comment by skorokithakis** [comment]
Let's discuss in #3.

**Comment by skorokithakis** [comment]
This has been implemented in master (as this PR was incomplete).

**Pull request closed without merging**
