### PR TITLE
feat: Extend features and behavior for Traversable objects

### PR DESCRIPTION
**Pull request by mumbleskates**
Revamp of #1 

* Commits broken up by lesser features
* Includes doctests in tox

Cherry picking will require review of readme. Test coverage is alright but not perfect.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Sorry, what's this new PR for? I'd like to merge the new operators now (in/dir/int/float/etc), but not the removal of `.r()`. The rationale behind the latter is that jsane can also work on Python objects, rather than just JSON, which may include functions, which means that you'd have to do `j.myfunc()()` to resolve and call it. Plus, it's more opaque/error-prone.

**Comment by mumbleskates** [comment]
You mentioned wanting to break it up and cherry pick changes. I broke it up into its constituent parts with a couple minor improvements and you see it here.

If you don't want to include the removal of `.r()` that's fine and you can exclude that commit, though I'm skeptical of using it with regular python objects since they already have an easy syntax, and this library mostly seems to facilitate working with structured json-like data.

I'm not sure what you mean by error-prone, however. Most of these errors are included with intent, as it is better to fail explicitly than silently coerce values or do the wrong thing.

**Comment by skorokithakis** [comment]
> If you don't want to include the removal of .r() that's fine and you can exclude that commit, though I'm skeptical of using it with regular python objects since they already have an easy syntax, and this library mostly seems to facilitate working with structured json-like data.

Yeah, this is definitely something I'm ambivalent about. it's not so much Python objects as it's Python dicts, but that's not very common a use case.

> I'm not sure what you mean by error-prone, however.

Mostly that `.r()` sticks out much more than `()`, and someone reading your code will immediately know that it's a jsane object you're reifying, instead of a function on a Python object that you're calling. Mostly in cases where someone passes a jsane object into a function, for example.

**Comment by skorokithakis** [comment]
Alright, i like this a lot, and I think it's good to merge. Can you check to see I haven't screwed anything up with the reversions? I'd like to keep both `.r()` and the callable interface, as it was before, but still incorporate your nice error checking.

**Comment by mumbleskates** [comment]
Fixed and improved the docs a little (to mention both resolution calls, make more sense, and also pass doctests) and re-added the other resolution variation's test lines in test_resolution.

**Comment by skorokithakis** [comment]
Fantastic, would you say this is good to merge?

**Comment by mumbleskates** [comment]
Far as I can tell this looks workable, yep.

**Comment by skorokithakis** [comment]
Fantastic, thank you!

**Pull request merged**
