### PR TITLE
Remove as much problematic text as possible

### PR DESCRIPTION
**Pull request by kennethlove**
No reason to provide that original motivation at all (code needs to work, it doesn't need to arouse anyone). And insane/sane is problematic in tone, best to avoid it.

### CODE REVIEW

**Comment by pdr** [comment]
👍  I agree.

**Comment by skorokithakis** [comment]
Jeez guys, it's the scene from [Swordfish](https://www.youtube.com/watch?v=rUY8HysBzsE)! Hasn't anyone seen that movie?

I don't mind changing the non-insane, though, if you want to change the PR to that.

**Comment by katylava** [comment]
I got it, and I laughed. Maybe add a footnote explanation for people who haven't seen the movie?

**Comment by skorokithakis** [comment]
@katylava That seems like a good compromise.

**Comment by skorokithakis** [comment]
I've changed this on master directly, thank you!

**Pull request closed without merging**
